# Generated by Django 4.2.8 on 2026-05-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genders_tbl',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.genders')),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='profile_pics/default_profile_pic.png', upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                
            ],
            options={
                'db_table': 'users_tbl',
            },
        ),
    ]
